### ISSUE TITLE
Virus safe ?

### ISSUE THREAD

**Issue by Suleman-Elahi** [NoakPalander/KeyboardLayoutSwitcher#1]
![image](https://user-images.githubusercontent.com/24384996/40484471-96420960-5f10-11e8-9ade-50d3900671aa.png)

Also, when launched, Windows 10 throws this error :(
 
![image](https://user-images.githubusercontent.com/24384996/40484531-be57d6e6-5f10-11e8-8a4c-c76cf30d96e5.png)

**Comment by NoakPalander** [comment]
Sorry for not seeing this until now. The program contains no virus what so ever, it's open source so everyone can check it out. Yet I've seen this error myself, while installing it on my secondary computer. Though it did work even without MSVCP140D.dll for me, I'll take a look at it.

**Comment by NoakPalander** [comment]
The problem is fixed for me. I decided to make an updated version of the layoutswitcher. You can see the rep at my profile, it's labeled "2.0". I decided to not include a setup-file since I had big issues creating one this time. Instead you'll just have to run the .exe file directly, the fastest option is the .exe in the release folder. The debugg should be working too but not to be used. The missing DLL's are included in the project folder.
